/**
 * ChainCheck — Contract Configuration (Sprint 1)
 *
 * Reads deployment info from deployment.json (generated by deploy script).
 * Exports contract address, intermediary address, and chain ID for frontend use.
 *
 * After running `npx hardhat run scripts/deploy.js --network localhost`,
 * this file will automatically pick up the deployed contract info.
 */

import deploymentInfo from "./deployment.json";

export const CONTRACT_ADDRESS = deploymentInfo.contractAddress;
export const INTERMEDIARY_ADDRESS = deploymentInfo.intermediary;
export const CHAIN_ID = deploymentInfo.chainId;
export const NETWORK = deploymentInfo.network;

// Hardhat local test account roles (for demo convenience)
export const DEMO_ACCOUNTS = deploymentInfo.accounts || {};
